### ISSUE TITLE
deploy Jenkins HPI file from master is broken

### ISSUE THREAD

**Issue by monperrus** [eclipse/repairnator#1020]
The CD script fails to deploy the Jenkins HPI file to https://repo.jenkins-ci.org/snapshots/fr/inria/repairnator/repairnator-jenkins-plugin/

See https://travis-ci.org/eclipse/repairnator/jobs/646792561

Some secrets are missing in the Travis configuration?

**Comment by henry-lp** [comment]
We can discuss on tuesday. 

I just test deploy `repairnator-jenkins-plugin` on my private repo and it works fine.

[git repo](https://github.com/henry-lp/testrelease)
[Success travis build](https://travis-ci.org/henry-lp/testrelease/builds/647711594)

**Comment by monperrus** [comment]
With the new environment variables, we still have a deployment problem, see https://travis-ci.org/eclipse/repairnator/jobs/648912620

WDYT?

**Comment by henry-lp** [comment]
@monperrus  I think we can try this fix (#1023)

**Comment by monperrus** [comment]
CD of jenkins plugin fixed: https://travis-ci.org/eclipse/repairnator/builds/648998583

Thanks!
