### ISSUE TITLE
new mode for fault-localization only

### ISSUE THREAD

**Issue by ssk1216** [eclipse/repairnator#1029]
The objective is on commit, it should build, then invoke Gzoltar to list the lines of code which are suspicious ..

Any suggestions???

**Comment by monperrus** [comment]
> Any suggestions?

1. Add a mode in the pipeline to have GZoltar fault localization only
2. Implement a Gitlab connector (with inspiration from the Jenkins connector
https://github.com/eclipse/repairnator/blob/master/doc/repairnator-jenkins-plugin.md)

**Comment by ssk1216** [comment]
Sorry ,could you please elaborate on the above points.
Is there any documentation available about how to invoke Gzoltar once a commit is done ? Is it the gitlab.ci.yml file which needs an edit ? If so any info on that

Also, if astor is to be invoked in the pipeline , what's the procedure for that?

**Comment by monperrus** [comment]
> Is there any documentation available about how to invoke Gzoltar once a commit is done?

No, this is not a use case we considered in the past.

> Also, if astor is to be invoked in the pipeline , what's the procedure for that?

See [AstorRepair](https://github.com/eclipse/repairnator/blob/master/src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/repair/astor/AstorRepair.java)

To achieve what you want, I'd suggest to study the different implementations of [AbstractRepairStep](https://github.com/eclipse/repairnator/blob/master/src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/repair/AbstractRepairStep.java) and how they are used in [ProjectInspector](https://github.com/eclipse/repairnator/blob/master/src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/inspectors/ProjectInspector.java)

**Comment by monperrus** [comment]
FTR, GZoltar has compatibility problems with recent JVMs, see https://github.com/SpoonLabs/nopol/issues/211
