### ISSUE TITLE
bug: Github app does not make PR on PRs

### ISSUE THREAD

**Issue by monperrus** [eclipse/repairnator#1031]
When a PR build fails, the Repairnator Github app does not make a PR on the PR because of:
https://github.com/eclipse/repairnator/blob/3df747b92a06ee1ff67bf6d8baea613dbc6edfc4/src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/repair/AbstractRepairStep.java#L129

It's true that a PR on a PR is not common, but at the same time most interesting failing builds to repair are on PR.

What could be a good user interface for this use case?

**Comment by jianguda** [comment]
Hey @monperrus 

As planned, GitHub app does not make PR on PRs.
Repairnator is able to do this thing alone, please check https://github.com/aaime/geowebcache/pull/1/.

> What could be a good user interface for this use case?

I feel the `lucesape`‘s comment template is still applicable.

**Comment by jianguda** [comment]
I feel that PR on PRs is one great idea.
