### ISSUE TITLE
continuous deployment on K8S from Travis

### ISSUE THREAD

**Issue by monperrus** [eclipse/repairnator#1039]
idea: we can automatically update the K8S worker when a commit is pushed to master, from the deployment script, with an encrypted secret in Travis.

@gluckzhang WDYT?

**Comment by gluckzhang** [comment]
Hi @monperrus , that sounds great. This should be done after the script pushes the built image to DockerHub. I will make a PR to solve this issue :)

To be updated:
- `kubectl` installed in Travis environment
- necessary configs like the k8s IP and credentials set by Travis UI (env value)

The command to be added after this line:
https://github.com/eclipse/repairnator/blob/59985e7a854c5e0d82c73a5472d611c9d2895c45/.travis/travis-deploy.sh#L47

```
kubectl delete pod $(kubectl get pods -n repairnator -l app=repairnator-pipeline -o custom-columns=NAME:.metadata.name --no-headers=true) -n repairnator
```

**Comment by monperrus** [comment]
that's a great plan, thanks Long!

**Comment by monperrus** [comment]
ping @gluckzhang ?

**Comment by gluckzhang** [comment]
Hi @monperrus , I am still working on this. I'll create a PR later today :)
The work is mainly inspired by https://codygreen.com/2018/08/13/ci-cd-with-kubernetes-and-travis-ci/

**Comment by monperrus** [comment]
cool! looking forward to it :)

**Comment by monperrus** [comment]
It works!

#1037 was merged, the K8S worker was automatically updated and the following PR was made with the new text: https://github.com/monperrus/failingProject/pull/13

Thanks a lot!
