### ISSUE TITLE
Jenkins plugin: add config parameter "email"

### ISSUE THREAD

**Issue by monperrus** [eclipse/repairnator#1041]
When using the Jenkins plugin in a non-Github plugin, the patch only appears in the log.

We can add an advanced config parameter "email": if a patch is found and we are not in a Github context, the patch is sent by email to the developers.

@henry-lp WDYT?

**Comment by henry-lp** [comment]
Yes , I'll add this new feature. Is this urgent ?  

If I can start in one or two week after my schedule loose up a bit, it would be perfect. :)

**Comment by monperrus** [comment]
Great, thanks Henry! No urgency here :-)
