### ISSUE TITLE
Repairnator development workflow: when to run the tests

### ISSUE THREAD

**Issue by gustavopinto** [eclipse/repairnator#1050]
Hi all,

my development workflow on Repairnator is still a lot manual. 

After I do some changes, I have to do ``mvn install``, then run the resulting jar in the command line. Running the test cases did not help me much, because they take some good time..

Is there any better way to run Repairnator?

**Comment by monperrus** [comment]
Hi Gustavo,

Yes, you never run all tests locally. You only run the test class you're currently working on. You can push branches on Github to run all tests (inside a WIP PR or as a separate PR).

**Comment by monperrus** [comment]
@gustavopinto could we close this old issue? (and the others as well?)

**Comment by gustavopinto** [comment]
Sure!
