### ISSUE TITLE
Continuous integration pipeline is flaky

### ISSUE THREAD

**Issue by monperrus** [eclipse/repairnator#1057]
As you all know, we have long-standing problems with the Repairnator CI:
- it's too slow
- it's flaky

Having look at the build time without tests (only dependencies & compile), the Docker pull jobs take ages.

So I propose to move all tests requiring docker to a separate repo for integration testing, it could be:
- a Travis job: https://github.com/repairnator/repairnator-integration-tests
- a Jenkins job: https://ci.eclipse.org/repairnator/job/repairnator-integration-test

WDYT?

**Comment by henry-lp** [comment]
I am on this :) .

**Comment by monperrus** [comment]
great!

**Comment by henry-lp** [comment]
Hi @monperrus 

I check a bit and only RTScanner have a docker test. 

Waiting for merging this PR (https://github.com/repairnator/repairnator-integration-tests/pull/2)

Also , it would be great if I have access to the repo https://github.com/repairnator/repairnator-integration-tests , so I can set up a CI pipeline :) .

**Comment by henry-lp** [comment]
Also, would you also want to move these test cases (they are unrelated to docker, but they are a bit heavy) ?

https://github.com/eclipse/repairnator/blob/17749319ba290695058b260aaf1063777c3938c9/src/repairnator-realtime/src/test/java/fr/inria/spirals/repairnator/realtime/TestRTScanner.java#L45-L103

**Comment by henry-lp** [comment]
Also, I just check and they seems to not have `Docker` installed on their slave pods on Eclipse Jenkins, because docker tests use [this dependency](https://github.com/spotify/docker-client) to build DockerRunnablePipeline and they require `Docker 1.6+` to run .

**Comment by monperrus** [comment]
great progress!

> Waiting for merging this PR (repairnator/repairnator-integration-tests#2)

merged, thanks

> Also , it would be great if I have access to the repo repairnator/repairnator-integration-tests 

added you as admin: https://github.com/repairnator/repairnator-integration-tests/invitations

> would you also want to move these test cases (they are unrelated to docker, 

not now (baby PR always :-)

> Perhaps we should go with a Travis job

yes, let's do this for now in https://github.com/repairnator/repairnator-integration-tests/

**Comment by monperrus** [comment]
Reopening this one, CI is again very flaky, more mocking is necessary. We can analyze the last 50 builds to identify the flaky tests to refactor.

**Comment by monperrus** [comment]
FYI
Root causing, detecting, and fixing flaky tests: State of the art and future roadmap
https://onlinelibrary.wiley.com/doi/abs/10.1002/spe.2929?af=R
