### ISSUE TITLE
Deploy jenkins plugin to sonatype

### ISSUE THREAD

**Issue by henry-lp** [eclipse/repairnator#1069]
I see that we already are using sonartype for deploying. Can we also deploy repairnator-jenkins-plugin to sonar-type so we keep everything in one place ? 

This would perhaps require someone to log in to the sonartype account of repairnator using currently to submit a ticket to also deploy it. 

@monperrus . WDYT ? :)

**Comment by monperrus** [comment]
Thanks for the proposal.

> Can we also deploy repairnator-jenkins-plugin to sonar-type so we keep everything in one place ?

I'm not sure. It makes a lot of sense to deploy the Jenkins plugin on the Jenkins repo.

Am I missing a killer advantage?

**Comment by henry-lp** [comment]
It's just that my temporary account for hosting on Jenkins expired today, so I thought perhaps we could just move it to sonar :) .

**Comment by monperrus** [comment]
Now I understand. If there is no way to have a permanent account on Jenkins, then we'll move to
either the Eclipse snapshot repo of the Sonatype one. I would prefer the Eclipse one. WDYT?

**Comment by henry-lp** [comment]
Yes , I agree that we deploy to eclipse :) .

**Comment by monperrus** [comment]
great. since you're official committer, you probably have all the rights to create the deployment
credentials.

**Comment by henry-lp** [comment]
I change my mind. Perhaps we can just deploy it to my git repo https://github.com/henry-lp/mvn-repo/tree/mvn-repo . :)

**Comment by monperrus** [comment]
Closing, it's now being deployed to the Github repo
