### ISSUE TITLE
Update Sonatype repo

### ISSUE THREAD

**Issue by javierron** [eclipse/repairnator#1076]
Pull request https://github.com/eclipse/repairnator/pull/1066 integrated Sonar repair as a repair tool. Specifically in this file https://github.com/eclipse/repairnator/commit/6e4d84c94f2d05589ee5aa88a91da43905e2cce1#diff-83192f0e3c251bc1f305558be1f6a23f it is added as a service (along with Sequencer Repair) to be discovered by the RepairToolManager.java class.

This changes are not available in the latest Sonatype deployment, and thus also not available in the current repairnator-pipeline docker image.

**Comment by javierron** [comment]
I think the problem is here: https://github.com/eclipse/repairnator/blob/8b238630fdc88b7c7c1e065da6d3aab0e750c06b/.travis.yml#L25

Ever since the travis file was updated here: https://github.com/eclipse/repairnator/pull/1060/files the deploy stage has never executed, and the repos/images never deployed.

The condition should be `env(TRAVIS_PULL_REQUEST) = false`. Patch incoming

**Comment by monperrus** [comment]
build restarted
