### ISSUE TITLE
multiple problems with CD deployment secrets

### ISSUE THREAD

**Issue by javierron** [eclipse/repairnator#1079]
Current CD is displaying the following message. It could have to do with the reason of the failure.

```
$ export OSS_REPAIRNATOR_PASSWORD=[secure]

We were unable to parse one of your secure environment variables.

Please make sure to escape special characters such as ' ' (white space) and $ (dollar symbol) with \ (backslash) .

For example, thi$isanexample would be typed as thi\$isanexample. See https://docs.travis-ci.com/user/encryption-keys.
```

**Comment by monperrus** [comment]
Thanks Henry! Let's see what happens with the latest merge.

**Comment by javierron** [comment]
```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```
Maybe if we try the `travis_wait` command here as well?

```
$ export OSS_REPAIRNATOR_PASSWORD=[secure]
We were unable to parse one of your secure environment variables.
```

It also keeps failing to parse the env variable :(

**Comment by monperrus** [comment]
Changed the password on https://oss.sonatype.org/ (user: spoon), updated Travis-ci.com config.
restarted latest job on master.

**Comment by monperrus** [comment]
We're making progress but nothing on https://oss.sonatype.org/content/repositories/snapshots/fr/inria/repairnator/repairnator-pipeline/3.3-SNAPSHOT/ yet

**Comment by monperrus** [comment]
Problem fixed: https://oss.sonatype.org/content/repositories/snapshots/fr/inria/repairnator/

Had to fight with credentials
