### ISSUE TITLE
Make Repairnator compile on Java >= 9

### ISSUE THREAD

**Issue by andre15silva** [eclipse/repairnator#1133]
Nopol requires tools.jar as a dependency.
This library was replaced in [JEP 220](https://openjdk.java.net/jeps/220).

When we try to compile Repairnator on a JDK which does not have tools.jar we get `BUILD FAILED`. Example, with OpenJDK 14:
`
ERROR] Failed to execute goal on project repairnator-pipeline: Could not resolve dependencies for project fr.inria.repairnator:repairnator-pipeline:jar:3.3-SNAPSHOT: Could not find artifact com.sun:tools:jar:1.4.2 at specified path /usr/lib/jvm/java-14-openjdk/../lib/tools.jar -> [Help 1]
`

Ideally, we should make Repairnator compile and run (except for Nopol) on any JDK version that does not have tools.jar (any OpenJDK or Oracle Java >= 9)

**Comment by monperrus** [comment]
This is a bug, because we build Nopol itself, so this should only be a runtime error (if using the Nopol repair tool), not a build time one.

**Comment by SophieHYe** [comment]
Hi @andre15silva,

Please note that there are two profiles in the pom.xml : nopol executed in jdk1.8 and noNopol executed in jdk1.9. 

If you are using Java >=9, which the tools.jar not included. Please try the following work-around which worked for me:

1. We set the active profile for noNopol by default in the pom.xml. First, please add the <activeByDefault> configure in both profiles as follows:
```
 <activation>
         <jdk>1.8</jdk>
        **<activeByDefault>false</activeByDefault>**
 </activation>

and 

<activation>
       <jdk>[1.9,1.16)</jdk>
       **<activeByDefault>true</activeByDefault>** 
</activation>
```

2. Let maven active the profiles by run the code:
```
 mvn help:active-profiles 
```

3. Then we can run mvn install -DskipTests as usual.
