### ISSUE TITLE
Eclipse committers

### ISSUE THREAD

**Issue by monperrus** [eclipse/repairnator#1157]
Reference page: https://projects.eclipse.org/projects/technology.repairnator/who

**Comment by monperrus** [comment]
Congrats to @javierron who is now an official Eclipse committer for Repairnator, see https://projects.eclipse.org/projects/technology.repairnator/who

@javierron what about adding a picture in your Eclipse profile?

**Comment by andre15silva** [comment]
Congrats @javierron !

**Comment by martinezmatias** [comment]
Great @javierron ! Felicitaciones!
