### ISSUE TITLE
Install junit-plugin in Jenkins

### ISSUE THREAD

**Issue by andre15silva** [eclipse/repairnator#1170]
https://github.com/jenkinsci/junit-plugin allows us to access test reports, which is a useful thing for quickly checking what the actual problem is without running the tests locally, and to get more information about non-reproducible errors.

**Comment by monperrus** [comment]
Excellent idea. @javierron WDYT?

**Comment by javierron** [comment]
That would be very helpful. I think the plugin is (available by default)[https://wiki.eclipse.org/Jenkins#Default_plugins_-_Jiro_.28ci-staging.eclipse.org.2Fxxx_and_ci.eclipse.org.2Fxxx.29].

**Comment by monperrus** [comment]
OK, it's available but not activated? @andre15silva would you have a look on how to activate it in our job? Thanks!

**Comment by andre15silva** [comment]
Didn't realize it was already available, sorry. I'm going to activate it in #1169.
