### ISSUE TITLE
Bump Java version to Java 11

### ISSUE THREAD

**Issue by andre15silva** [eclipse/repairnator#1186]
Related #371.

Need to be careful with `Nopol`.

**Comment by andre15silva** [comment]
@monperrus I can jump straight on this, as this is blocking compilation on `master`

**Comment by andre15silva** [comment]
This is actually trickier than I thought. It breaks more than Nopol switching to Java 11, particularly tests. Needs further analysis.

**Comment by monperrus** [comment]
I'm not surprised that a few tests need to be adapted.

**Comment by monperrus** [comment]
Per our conversation with @javierron, on Astor, we may have problems with GZoltar, which means we would revive @martinezmatias 's essential long-term work on Flacoco, see #1116
