### ISSUE TITLE
ARJA for Repairnator

### ISSUE THREAD

**Issue by byteSamurai** [eclipse/repairnator#1193]
Hey,
just a question: Is ARJA relevant/interesting for Repairnator? I havn't verified the results in the paper, but it looks promising, compared to jGenProg (no offense). 

https://github.com/yyxhdy/arja

What do you think?

**Comment by monperrus** [comment]
Welcome! Yes, Arja is relevant for Repairnator.

> I havn't verified the results in the paper, but it looks promising, compared to jGenProg

Which paper are you referring to?

**Comment by byteSamurai** [comment]
This one: https://ieeexplore.ieee.org/document/8485732/ 

I was just curious as repairThemAll uses ARJA as well as ARJA's variant implementations for example Genprog-A

**Comment by monperrus** [comment]
Arja is a great tool! but I would suggest to take the experimental results of this paper with a 
grain of salt.

Per our experience with Arja, it tends to regularly produce patches that are actually not plausible 
(perhaps because they don't run the whole test suite, hypothesis to be verified)

**Comment by fermadeiral** [comment]
> I was just curious as repairThemAll uses ARJA as well as ARJA's variant implementations for example Genprog-A

About RepairThemAll, it's just a framework to run different repair tools on different datasets of bugs, for experimental purposes. The repair tools plugged in RepairThemAll are the ones that meet some basic criteria, like being publicly available. In other words, we didn't choose repair tools that are good or better than other ones to include in RepairThemAll, we just choose the ones that we could properly plugged in the framework.

**Comment by byteSamurai** [comment]
@fermadeiral I see your point. Sorry for the noise
