### ISSUE TITLE
release repairnator-core on Maven Central

### ISSUE THREAD

**Issue by monperrus** [eclipse/repairnator#1202]
For @cokefh to use maven-repair at Ericsson, we need to deploy a version of it with no dependency to any snapshots.

For this, we need to release repairnator-core 3.3 on Maven Central.

@andre15silva would you be able for this?

Thanks!

**Comment by andre15silva** [comment]
> @andre15silva would you be able for this?

Yes, no problem! How do I authenticate?

**Comment by monperrus** [comment]
We will use a Sonatype token from Sonatype user `spoon-bot`, could you send me your GPG key so that I can share the token with you?

**Comment by andre15silva** [comment]
> could you send me your GPG key so that I can share the token with you?

Sent!

**Comment by andre15silva** [comment]
I've deployed the release, but it's taking a lot of time to show up. 

I also deployed a snapshot, and it was almost instant to show up.

**Comment by cokefh** [comment]
> I've deployed the release, but it's taking a lot of time to show up.
> 
> I also deployed a snapshot, and it was almost instant to show up.

Thank you Andre, I got it running locally now. It’s really good to have it with a release to have it running in Ericsson system. FH

**Comment by monperrus** [comment]
Thanks @andre15silva updated #1201 accordingly.

**Comment by andre15silva** [comment]
Note that the release hasn't appeared in maven central yet. I'm reading that it can take up to two hours to sync, but it's been way more than that... (I've tried deploying again too)

**Comment by monperrus** [comment]
still not on central, something has failed.

**Comment by andre15silva** [comment]
> still not on central, something has failed.

Could you check the [staging repository](https://oss.sonatype.org/#stagingRepositories)? From my end it uploads to staging correctly.

**Comment by andre15silva** [comment]
Released on central, at last.

**Comment by monperrus** [comment]
@andre15silva now that exceptionparser is in core (https://github.com/eclipse/repairnator/pull/1216), could you release core again on Central?

Then, we'll be able to finish a maven repair plugin with clean dependencies (https://github.com/eclipse/repairnator/pull/1201).

Thanks!

**Comment by andre15silva** [comment]
`repairnator-core` 3.4 released!

**Comment by monperrus** [comment]
Thanks a lot. Updated #1201 accordingly, hopefully it is green.
