### ISSUE TITLE
CI should not use anonymous connections to Gtihub (PatchFilterTest)

### ISSUE THREAD

**Issue by monperrus** [eclipse/repairnator#1253]
CI should not use anonymous connections to Gtihub (https://github.com/eclipse/repairnator/search?q=connectAnonymously), because it is heavily rate limited (many other Eclipse projects use the same IP).

Instead `PatchFilterTest` should use the credentials stored  in Jenkins.

**Comment by monperrus** [comment]
@Sofi1410 would you be able to fix this? @javierron  can likely help you. Thanks!

**Comment by Sofi1410** [comment]
Added to the list :)
