### ISSUE TITLE
CI is broken on master August 2022

### ISSUE THREAD

**Issue by monperrus** [eclipse/repairnator#1254]
CI is broken on master for a number of reasons. I already fixed a few issues. It's not finished

* [x] dependencies https://github.com/eclipse/repairnator/commit/388315dd577e5e3af0b370fc45b94a7a9259bf77 https://github.com/eclipse/repairnator/commit/1bdf424ca6e8bd439611a768e27b7f060e7433de
* [x] broken tests due to disappeared api.travis.org https://github.com/eclipse/repairnator/commit/461111d415145fb3742101a596bfb96105c9d70f
* [x] CI uses anonymous connnections to Gtihub, see https://github.com/eclipse/repairnator/issues/1253
* [x] SSL certificate of sachaproject.gforge.inria.fr outdated

**Comment by monperrus** [comment]
> [ERROR] Failed to execute goal on project repairnator-realtime: Could not resolve dependencies for project fr.inria.repairnator:repairnator-realtime:jar:3.3-SNAPSHOT: Failed to collect dependencies at fr.inria.repairnator:repairnator-pipeline:jar:3.3-SNAPSHOT -> org.inria.sacha.automaticRepair:astor:jar:20190919 -> fr.inria.gforge.spirals:nopol:jar:0.2-SNAPSHOT -> com.microsoft.z3:z3:jar:0.0.1: Failed to read artifact descriptor for com.microsoft.z3:z3:jar:0.0.1: Could not transfer artifact com.microsoft.z3:z3:pom:0.0.1 from/to gforge.inria.fr-release (http://sachaproject.gforge.inria.fr/repositories/releases/): Transfer failed for http://sachaproject.gforge.inria.fr/repositories/releases/com/microsoft/z3/z3/0.0.1/z3-0.0.1.pom: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed: NotAfter: Thu Aug 25 23:59:59 UTC 2022 -> [Help 1]

SSL certificate of sachaproject.gforge.inria.fr outdated, sent an email to Inria

**Comment by monperrus** [comment]
certificate of sachaproject.gforge.inria.fr renewed

**Comment by Sofi1410** [comment]
FYI: 
CI uses anonymous connnections to Gtihub, see https://github.com/eclipse/repairnator/issues/1253 is already fixed on https://github.com/eclipse/repairnator/pull/1256
