### ISSUE TITLE
first snippet in documentation

### ISSUE THREAD

**Issue by monperrus** [eclipse/repairnator#1262]
Hi all,

In the landing doc page of Repairnator https://github.com/eclipse/repairnator/tree/master/doc
the first snippet is 

    mvn exec:java -Dexec.mainClass=fr.inria.spirals.repairnator.pipeline.Launcher -Dexec.args="--buildId=235838150"

This is for Travis and Travis is dead :skull: .

It would be great to replace this first snippet by a class taking a commit id as input.

    mvn exec:java -Dexec.mainClass=fr.inria.spirals.repairnator.pipeline.Launcher -Dexec.args="--project=org/myproject --commit=eaa16725243ddddeeeeee"

Do we already have this?

ping @javierron @khaes-kth @Sofi1410 @andre15silva @algomaster99 @dginelli

**Comment by algomaster99** [comment]
I am not sure. Maybe others can take a look.

**Comment by khaes-kth** [comment]
> mvn exec:java -Dexec.mainClass=fr.inria.spirals.repairnator.pipeline.Launcher -Dexec.args="--project=org/myproject --commit=eaa16725243ddddeeeeee"

Not exactly this, but we have a mode in which we can run the launcher using a Github slug and commit id for Sorald. [This ](https://github.com/eclipse/repairnator/blob/master/src/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/SimplePipelineRunner.java#L48) is how it is called in the code. I think @Sofi1410 used this recently for her tool.

**Comment by Sofi1410** [comment]
Like @ khaes-kth mentioned, we have a mode for that, but we are increasing the data to run Repairnator. So a class for it might be a solution. 

Anyways, I'm confused about the question.

You are asking if we can add another way to run the tool by only giving a commit?

**Comment by monperrus** [comment]
the primary goal is to replace the current first snippet by a better one, unrelated to travis.

that may imply writing a bit more code to have a clean one-liner.

**Comment by andre15silva** [comment]
Hi all,

AFAIU, there are two tasks here:

- The `BranchLauncher` is the launcher that is executed with that command. In there, we branch according to the `launcherMode` option: https://github.com/eclipse/repairnator/blob/56735a9db9b54b65a4a186f4f865bcd954e33883/src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/pipeline/BranchLauncher.java#L57-L88

	The default for this option is `LauncherMode.REPAIR`. As you can see in the code above, this option launches a `TravisMainProcess`, which is not what we want to do.

	The option we want to use if `LauncherMode.GIT_REPOSITORY`, which launches a `GitHubMainProcess`.
Right now, to execute this we could use the following command:
	```
	mvn exec:java -Dexec.mainClass=fr.inria.spirals.repairnator.pipeline.Launcher -Dexec.args="--launcherMode GIT_REPOSITORY --gitrepourl https://github.com/andre15silva/failingProject --gitrepoidcommit fda5d6161a5602a76e810209491d04cf91f4803b"
	```

	IMO, we should move the default to be `LauncherMode.GIT_REPOSITORY`. This will be a breaking change.

- When using the command above, we face another issue: the default repair tools. Right now, it appears that `NPEFix` is the default repair tool, but I am not finding where it is defined.

	My question here is: which tool or set of tools do we want to have as default?
