### ISSUE TITLE
DockerHub images may be deleted

### ISSUE THREAD

**Issue by andre15silva** [eclipse/repairnator#1264]
Docker is deleting docker hub organizations that are on their legacy free tier: https://blog.alexellis.io/docker-is-deleting-open-source-images/
I have also received an email about this

This is not good for us because we depend on these images for several parts of Repairnator (e.g. repairnator/pipeline, repairnator/ci-env) 

Our org: https://hub.docker.com/orgs/repairnator/repositories

There is an Open Source program that I have applied repairnator to (https://www.docker.com/community/open-source/application/), but I'm not sure we meet the "active development" criteria nor that they will respond in time.

**Comment by andre15silva** [comment]
Nevermind! They were quick to respond. We have been approved for the Docker-Sponsored Open Source program.


Important: **"please take the time to update your project’s Hub pages to include a detailed project description, links to your project source code, as well as contributing guidelines, and a link to your organization’s website. Projects lacking this information may not receive the Docker Sponsored Open Source badging for their images on Docker Hub."**

@monperrus I don't seem to have permission to do this. Would you be able to add permissions?

**Comment by monperrus** [comment]
@andre15silva added you as owner on Dockerhub
