### ISSUE TITLE
Travis is not working with regular pull requests

### ISSUE THREAD

**Issue by monperrus** [eclipse/repairnator#744]
It's confusing to contribute to Repairnator, because CI fails for external pull-requests. 

Spin-off of @fermadeiral comment: https://github.com/Spirals-Team/repairnator/issues/579#issuecomment-396992772

**Comment by fermadeiral** [comment]
First trial could be the long term view described in https://github.com/Spirals-Team/repairnator/issues/579#issuecomment-397203137

**Comment by monperrus** [comment]
with the community expansion, this is becoming super high priority.

**Comment by monperrus** [comment]
Fixed, #983 is a proof.
