### ISSUE TITLE
feature: feedback collect for patches proposed in PR 

### ISSUE THREAD

**Issue by monperrus** [eclipse/repairnator#800]
in pull requests, add links to collect feedback

* [x] feedback collection implementation on Azure
* [x] feedback collection protected by Captcha
* [x] feedback  links
* [x] collect feedback in append-only manner
* [x] document the feedback collection infrastructure

**Comment by bloriot97** [comment]
Maybe I can do it with @btellstrom.
I can take care of creating a route in the API to upvote/downvote a patch depending on it's _id.
Then we would just need to put the different links in the email depending on the _id of the patch. 

WDYT?

**Comment by monperrus** [comment]
very good plan!

**Comment by bloriot97** [comment]
Also, do you think we should implement a system of token to avoid a single user to vote several times? 

It is not much to code but it would increase the maintenance because we would need to share a secret between the rest api and repairnator. 

For now, I think this is not especially necessary.

**Comment by monperrus** [comment]
let's KISS <https://en.wikipedia.org/wiki/KISS_principle> it.

**Comment by monperrus** [comment]
> In RefBot ("[RefBot: Intelligent Software Refactoring Bot](https://2019.ase-conferences.org/details/ase-2019-papers/46/RefBot-Intelligent-Software-Refactoring-Bot)") when a pull-request is made, it analyses the changed files and proposes changes. The developer can then follow a link to an external UI where she can approve or deny individual changes of the PR.

**Comment by monperrus** [comment]
updated text!

**Comment by monperrus** [comment]
we need to change the title from "Repairnator" to "R-Hero"

**Comment by monperrus** [comment]
"Patch automatically synthesized by R-Hero :tophat:" in both title and description

**Comment by monperrus** [comment]
New template is at https://github.com/eclipse/repairnator/pull/1124

**Comment by monperrus** [comment]
Code and some doc in https://github.com/repairnator/r-hero-feedback-service

We're done for now!
