### ISSUE TITLE
integrate sequencer in Repairnator

### ISSUE THREAD

**Issue by monperrus** [eclipse/repairnator#844]
Given the very good results of [Sequencer](http://arxiv.org/pdf/1901.01808), we can integrate it in Repairnator.

**Comment by btellstrom** [comment]
To integrate Sequencer we may take two approaches, running docker from within the docker pipeline image or adding the dependencies to the docker image. For the long term, it would perhaps be better to be able to run docker from docker to ease the addition of new repair tools, and make the docker image less specific.

After discussing this issue, I and @monperrus have decided that adding the dependencies to the docker image is the easier solution for now, as we mostly want Repairnator to go forward, and spending time on getting docker in docker to work properly might be too time consuming for our current goals.

**Comment by jaxxgu** [comment]
Hey @btellstrom 
Is anyone in charge of this issue now? If not, I will deal with this.

**Comment by monperrus** [comment]
FYI, the part related to fault localization is at https://github.com/SpoonLabs/astor/tree/master/src-3sfix

**Comment by jaxxgu** [comment]
Hey @monperrus 
Could you please release one new version of Astor? Thanks in advance.

**Comment by jaxxgu** [comment]
i will try the solution described in [this post](https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/)

**Comment by monperrus** [comment]
Just released 1.0.0-SNAPSHOT: https://github.com/tdurieux/maven-repository/tree/master/snapshots/org/inria/sacha/automaticRepair/astor/1.0.0-SNAPSHOT

**Comment by jaxxgu** [comment]
I tried one [docker-in-docker demo](https://github.com/jaxxgu/demo/tree/master/dind) and it works.

**Comment by monperrus** [comment]
clsoed per #932
