### ISSUE TITLE
question: does the pipeline stop after the first successful repair attempt?

### ISSUE THREAD

**Issue by monperrus** [eclipse/repairnator#880]
For weeks, we mostly have kali patches from NopolAllTests.

This is boring and surprising because the other tools should also find some patches, starting with NpeFix and also with the kali patches of jGenProg.

Why do we have no jGenProg-kali patches?

Does the pipeline stop after the first successful repair attempt?

(anyway, we may disable NopolAllTests for now to debug the other tools)

**Comment by btellstrom** [comment]
This might be my fault. The current configuration only uses NopolAllTests, AstorJMut and NPEFix. These values are the default in the [config](https://github.com/Spirals-Team/repairnator/blob/master/repairnator/scripts/config/repairnator.cfg) and I had for some reason assumed that these were the tools that you and Simon had decided upon using or something of that nature.
