### ISSUE TITLE
IP addresses of Repairnator components in production

### ISSUE THREAD

**Issue by monperrus** [eclipse/repairnator#895]
Information about production (we can update this first comment directly)

* [x] ActiveMQ 137.74.202.216
* [x] NodeJS Github app 137.74.202.216
* [x] Kubernetes
  * Kubernetes master, WASP cloud, 129.192.71.76
  * Kubernetes workers, WASP cloud, X.Y.Z.Z (private IPs)
* [ ] MongoDB X.Y.Z.Z
* [ ] RTScanners
* [ ] RTDashboard X.Y.Z.Z

**Comment by gluckzhang** [comment]
Hi @monperrus ,
The IP address of the Kubernetes master is `129.192.71.76`. All the K8s workers only have internal IPs, because K8s automatically helps us to expose services :)
