### ISSUE TITLE
feat: add support for pushing into ActiveMQ in ProjectScanner

### ISSUE THREAD

**Issue by monperrus** [eclipse/repairnator#896]
for @Tailp

**Comment by Tailp** [comment]
@monperrus @gluckzhang hi :) , to dockerize this I need help deploying the new pipeline and project scanner component to our maven [repository](https://mvnrepository.com/artifact/fr.inria.repairnator), since I am not authorized.

**Comment by monperrus** [comment]
> I need help deploying the new pipeline and project scanner component to our maven repository
> <https://mvnrepository.com/artifact/fr.inria.repairnator>
this is done automatically when merged to master (job deploy in Travis).

**Comment by Tailp** [comment]
> I need help deploying the new pipeline and project scanner component to our maven repository <https://mvnrepository.com/artifact/fr.inria.repairnator>
> this is done automatically when merged to master (job deploy in Travis).

Hi :) , but from the look of it the most recent one is from last year Aug, 2018 for the scanner. <https://mvnrepository.com/artifact/fr.inria.repairnator/repairnator-scanner> . also when I test downloading the latest version into a jar and run it, it does not contain the new options we merged yesterday.

**Comment by monperrus** [comment]
The SNAPSHOT is the latest: https://oss.sonatype.org/content/repositories/snapshots/fr/inria/repairanator/repairnator-pipeline/
