### ISSUE TITLE
java.lang.ClassNotFoundException reported by Repairnator

### ISSUE THREAD

**Issue by dginelli** [eclipse/repairnator#973]
Running Repairnator with the repair tool AstorJGenProg, I obtained a java.lang.ClassNotFoundException due to the lack of class MaxLcsSimSearchStrategy, that is given as ingredient strategy in [these lines](https://github.com/eclipse/repairnator/blob/0f6f58e475d4806304289810f8abaa3ed53d6838/repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/repair/astor/AstorRepair.java#L91-L92) of Repairnator source code.

Removing these lines, the exception doesn't occur. 

You can see the entire log associated with the execution on build 564711868, and in particular the line in which the exception is reported, [here](https://gist.github.com/dginelli/d4e4052d49026131d92bdb82a1aae316#file-repairnator1-log-L101).

**Comment by martinezmatias** [comment]
Hi @dginelli 
Great. This strategy was used only in test cases. For this reason it's not included in the distribution jar.
Thanks
Matias

**Comment by monperrus** [comment]
Could you make a Pull-request with this fix? Thanks!
