### ISSUE TITLE
ERROR f.i.s.r.p.m.o.MavenFilterOutputHandler reported by Repairnator

### ISSUE THREAD

**Issue by dginelli** [eclipse/repairnator#974]
I tried to run Repairnator on different builds, but every time, during the first phases of the process, I noticed the error "ERROR f.i.s.r.p.m.o.MavenFilterOutputHandler - [INFO] Downloading from central: \<URL\>".

You can see an example in [these lines](https://gist.github.com/dginelli/e571dd672ba68cf45f0e7217335f9214#file-repairnator2-log-L43-L52) of the log associated with the execution on build 265094794.

However, after these errors, the process keeps going, generating the Repairnator files at the end.

I ran Repairnator using the parameters BUILD_ID, GITHUB_OAUTH, REPAIR_TOOLS, and PUSH_URL.

I don't know if I'm doing something wrong or not.

**Comment by dginelli** [comment]
Hi Martin,

I think I figured out why Repairnator prints the error message `"ERROR f.i.s.r.p.m.o.MavenFilterOutputHandler` in the console.

As you can see, in [this method](https://github.com/eclipse/repairnator/blob/c34c1497fce6fc913694fd3c486ff9ab6a0d63c1/src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/maven/output/MavenFilterOutputHandler.java#L16) there is [this if condition](https://github.com/eclipse/repairnator/blob/c34c1497fce6fc913694fd3c486ff9ab6a0d63c1/src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/maven/output/MavenFilterOutputHandler.java#L19), that checks if a string contains the word "error" or "ERROR". 

If so, Repairnator uses the instruction `this.getLogger().error(s);` to print the error message in the console.

The problem is that it's not always true that if there is the word "error", it is a real error. For instance, if you look at [these lines](https://gist.github.com/dginelli/e571dd672ba68cf45f0e7217335f9214#file-repairnator2-log-L43-L52) of the log file, in that case the word `error` was in the line associated with the download of a dependency that contains the word `error` in its name (`maven-error-diagnostics-2.0.6`).

Another example is [this line](https://gist.github.com/dginelli/e571dd672ba68cf45f0e7217335f9214#file-repairnator2-log-L57): in this case the word `error` is in the name of a test class, so it's not a real error.

An example in which it could be correct to print the error message can be [this one](https://gist.github.com/dginelli/e571dd672ba68cf45f0e7217335f9214#file-repairnator2-log-L209). Indeed, in this case there was a failing test case.

Maybe, we could change the if condition, and check for the presence of the token `[ERROR]` or `[error]`, instead of `ERROR` or `error`, but I'm not 100% sure that we can manage all the possible cases also in this way.

If you think that it could be a good idea to try to change the if condition as I described above, I can create a pull request and check if it passes all the test cases or not.

**Comment by monperrus** [comment]
> we could change the if condition, and check for the presence of the token [ERROR] or [error], instead of ERROR or error,

Great idea, please do a PR!
