### ISSUE TITLE
ERROR f.i.s.r.p.m.output.MavenErrorHandler reported by Repairnator

### ISSUE THREAD

**Issue by dginelli** [eclipse/repairnator#975]
Sometimes, when I ran Repairnator, I obtained this error: "ERROR f.i.s.r.p.m.output.MavenErrorHandler".

You can see some examples on this log file associated with the execution on the build 265094794 using the repair tool AstorJKali ([first example](https://gist.github.com/dginelli/e571dd672ba68cf45f0e7217335f9214#file-repairnator2-log-L53-L55), and [second example](https://gist.github.com/dginelli/e571dd672ba68cf45f0e7217335f9214#file-repairnator2-log-L65)).

It seems that they are errors related to the build and not to Repairnator itself, but I reported here in order to verify this aspect.

**Comment by monperrus** [comment]
How to fix this issue?

**Comment by monperrus** [comment]
closing stale issue
