### ISSUE TITLE
Advice about README

### ISSUE THREAD

**Issue by dginelli** [eclipse/repairnator#976]
This is just an advice about the README: the example command in the section [Fixing a build](https://github.com/eclipse/repairnator/blob/master/doc/README.md#fixing-a-build) (in which it is explained how to run repairnator-pipeline using its Docker image) has not the parameter GITHUB_OAUTH. 

Since without this parameter Repairnator generates some authentication errors,  in my opinion, it could be useful to add the parameter to the example (as reported in the [Repairnator.cfg section](https://github.com/eclipse/repairnator/blob/master/doc/repairnator-config.md#github_oauth)).

Finally, it could be useful to add a section in which to put all the environment variables that can be configured via command line when repairnator/pipeline is run with Docker.

**Comment by monperrus** [comment]
Thanks for noticing this. Documentation PR are welcome and super useful!

**Comment by monperrus** [comment]
Could you make a PR to close this issue? Thanks!

**Comment by dginelli** [comment]
Hi Martin, I have just created a pull request with the changes to the documentation. I noticed that the link present in the section [What Is Repairnator Doing Right Now?](https://github.com/eclipse/repairnator/blob/master/doc/repairnator-short-overview.md#what-is-repairnator-doing-right-now) doesn't work, so let me know if I have to change it with another one or not.
