### ISSUE TITLE
add support for Github app

### ISSUE THREAD

**Issue by monperrus** [eclipse/repairnator#978]
We need to add code to be able to deploy Repairnator as a Github app.

The application is registered at the organization or at the user level.

<s>It's NOT a Github webhook or a Travis webhook.</s>

## Activation

Visit https://github.com/apps/repairnator-bot aand click on the green button "Install"

## How it works?

If the build is failing and is in Java, it pushes the build id to an ActiveMQ. Then, the default pipeline worker with ActiveMQ can pick it.

**Comment by monperrus** [comment]
Documentation: https://developer.github.com/apps/

**Comment by monperrus** [comment]
Luc has created the app: https://github.com/apps/repairnator-app

**Comment by jianguda** [comment]
Based on the repairnator's arch diagram (from henry)
![unnamed](https://user-images.githubusercontent.com/9079360/71549970-078af780-29c7-11ea-8df1-e7db9401b3f5.png)

There are two ways:
1. NodeJS Server feeding failed travisCI builds to `BuildRainer.java`, like [tdurieux/travis-listener](https://github.com/tdurieux/travis-listener/)
2. Java Server pushing failed travisCI builds to MQ directly, equivalent to `RTScanner.java`

It seems very recommended to use JS for building GitHub app, so I will take the first way.

**Comment by monperrus** [comment]
> It seems very recommended to use JS for building GitHub app

That's a valid option. Although a JVM language (Java/Scala/Kotlin) would be a preferred option for
providing unified maintenance and deployment.

**Comment by jianguda** [comment]
I have been familiar with the work for building GitHub app. I will turn to the second way.

**Comment by jianguda** [comment]
Maybe I will still use the first way, because current/popular solution relies on Probot, one framework for building GitHub Apps. (or else we have to implement some necessary parts in that framework, such as receiving and validating webhooks, and doing authentication, etc.)

**Comment by monperrus** [comment]
that's an excellent idea to reuse a dedicated framework such as probot.

**Comment by jianguda** [comment]
app implementation and WebSocket demo:
https://github.com/jianguda/repairnator-bot
one repo for testing:
https://github.com/jianguda/repairnator-bot-test

**Comment by monperrus** [comment]
Per our discussion, we don't need websockets, we don't need BuildRainer.

Actions:

* push to ActiveMQ
* move the code from https://github.com/jianguda/repairnator-bot to a WIP PR here
* Run the app on the KTH Box in 1548 (See with @javierron)

**Comment by jianguda** [comment]
For the issue that other accounts' events can not not trigger our GitHub app, I guess it might be caused by travis API (acces issue). I even have received positive reply from `support@travis-ci.com`.

However, it is weird if we can see others' build log via web browser but can not request results via API. I tried travis API with API tester today, and received normal results of other accounts. I also tried WebServer and everythings work normally, but it can not even once yesterday. How confusing!

**Comment by monperrus** [comment]
yes, in Repairnator we use a lot of new or rarely used APIs and we find bugs :-)

**Comment by jianguda** [comment]
I have updated some implementations ([push to ActiveMQ directly](https://github.com/jianguda/repairnator-bot/commit/7e55cca93ea20331bae50b85d88faa481691a5ec)). Besides, I have improved [the README file](https://github.com/jianguda/repairnator-bot/blob/master/README.md). The work is almost done.

Because KTH box can not get access to the Internet, I copied some files, such as `repairnator.cfg`. I am going to do the final test on my laptop. After that, I will push the code to this repo.

**Comment by jianguda** [comment]
I have tested directly pushing to ActiveMQ and it works well. However, I did not test along with the whole Repairnator. In addition, travisCI's 403 issue happened again today.

**Comment by monperrus** [comment]
@gluckzhang is deploying the worker, and see also doc at https://github.com/eclipse/repairnator/pull/1021.

**Comment by gluckzhang** [comment]
Hi @jianguda ,
The messages your github app pushes to ActiveMQ will be handled by a repairnator pipeline. Could you document the format of these messages?

- What type: byte array / plain text?
- What format: JSON?

Thank you!

**Comment by monperrus** [comment]
Note: we need to keep full backward compatibility with the format already implemented in the
BuildRainer.

**Comment by gluckzhang** [comment]
Both BuildRainer and RepairnatorScanner only push build ids to the queue. How about

- adjusting github app to push build ids in plain text as well?  
- OR enhancing [PipelineBuildListener.java](https://github.com/eclipse/repairnator/blob/master/repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/pipeline/PipelineBuildListener.java) to check whether a message is formatted as JSON. Now the JSON string pushed by github app contains the source of a build id (travis.org / travis.com), but I am not sure if this is useful for the pipeline.

Which idea do you prefer? @monperrus @jianguda

**Comment by monperrus** [comment]
I'd go for Option 2 (enhancing PipelineBuildListener.java). Pushing structured JSON data is more
extensible, we will likely enrich this format later.

**Comment by gluckzhang** [comment]
Agree. I'll enhance the PipelineBuildListener and propose a PR later :)

**Comment by gluckzhang** [comment]
Hi @monperrus , please take a look at #1026 :)

@jianguda, FYI, now `PipelineBuildListener` supports a JSON string like `{"buildId":"648902893","CI":"travis-ci.org"}`.

**Comment by jianguda** [comment]
> Hi @monperrus , please take a look at #1026 :)
> 
> @jianguda, FYI, now `PipelineBuildListener` supports a JSON string like `{"buildId":"648902893","CI":"travis-ci.org"}`.

Nice! Thanks!

**Comment by monperrus** [comment]
done per #1009 we will create new issues for bugs
